name: candlecatch
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_3d_carousel: ^2.1.0 #キャンドル表示に使用

  cached_network_image: ^3.3.0 #      〃

  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_hooks: ^0.21.3+1

  # firebaseパッケージを追加
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  share_plus: ^10.0.0

  flutter_lints: ^5.0.0

  swipe_cards: ^2.0.0+1

  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/signInPageImage.png
    - images/

  fonts:
    - family: Corporate Logo Rounded Bold
      fonts:
        - asset: fonts/Corporate-Logo-Rounded-Bold-ver3/Corporate-Logo-Rounded-Bold-ver3.otf
