// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhY9MMA8S1Gmo2PLa0PNEcnS4RcXzQ4w',
    appId: '1:218998110533:web:20f947e3c6f177a644a62c',
    messagingSenderId: '218998110533',
    projectId: 'candle-catch',
    authDomain: 'candle-catch.firebaseapp.com',
    storageBucket: 'candle-catch.firebasestorage.app',
    measurementId: 'G-P4747QTDJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszCsgdU4UlolEVZwy6j_EOemxnj9H5tI',
    appId: '1:218998110533:android:56343ec4731f32e244a62c',
    messagingSenderId: '218998110533',
    projectId: 'candle-catch',
    storageBucket: 'candle-catch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvCLmxO4TQmDiGxa2RtjxKSSwSmRQ8JbM',
    appId: '1:218998110533:ios:5b68876179faa83c44a62c',
    messagingSenderId: '218998110533',
    projectId: 'candle-catch',
    storageBucket: 'candle-catch.firebasestorage.app',
    iosBundleId: 'com.example.candlecatch',
  );
}
